[package]
name = "sfs"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
serde = { version = "1", features = [ "derive" ] }
fuser = "0.11"
bincode = "1.3.3"
rocksdb = "0.18.0"
bitintr = "0.3.0"
